### ISSUE TITLE
Message from member null

### ISSUE THREAD

**Issue by rjwvandenberg** [JJ173/HaakuBotProject#1]
Received following error in bot:
```
/src/bot_modules/officer_module.js:12
	if(!message.member.roles.some(r=>officerRoles.includes(r.name))) return;
	                  ^

TypeError: Cannot read property 'roles' of null
    at Object.exports.run (/src/bot_modules/officer_module.js:12:20)
    at Client.client.on.message (/src/init_bot.js:60:13)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (/src/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/src/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/src/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (/src/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
    at WebSocket.onMessage (/src/node_modules/ws/lib/EventTarget.js:99:16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
```
Not sure under what conditions member is null, but it is a possibility, refer to Member datastructure:
https://github.com/hydrabolt/discord.js/blob/master/src/structures/Message.js

**Comment by rjwvandenberg** [comment]
Possible fix to make sure member exists: https://github.com/JJ173/HaakuBotProject/pull/2
