### ISSUE TITLE
Bot does not handle the error event.

### ISSUE THREAD

**Issue by rjwvandenberg** [JJ173/HaakuBotProject#8]
Encountered the following error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT <ip:port cut out>
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```
Implement client.on('error') logic. https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-error

**Comment by rjwvandenberg** [comment]
The following error falls under the same handler:

```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25)
```

**Comment by JJ173** [comment]
Should give error feedback now, it's been added in to the init_bot.js
